


export const fetchAlbuns = [
  {
    id: 1,
    title: "Acabou o Chorare",
    genre: "MPB",
    band: "Novos Baianos",
    price: "137.91",
    img: "https://openmusic-fake-api.onrender.com/_id1.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 2,
    title: "Minas",
    genre: "MPB",
    band: "Milton Nascimento",
    price: "94.74",
    img: "https://openmusic-fake-api.onrender.com/_id2.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 3,
    title: "Elis & Tom",
    genre: "MPB",
    band: "Elis Regina e Tom Jobim",
    price: "79.99",
    img: "https://openmusic-fake-api.onrender.com/_id3.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 4,
    title: "Thriller",
    genre: "Pop",
    band: "Michael Jackson",
    price: "142.32",
    img: "https://openmusic-fake-api.onrender.com/_id4.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 5,
    title: "Bad",
    genre: "Pop",
    band: "Michael Jackson",
    price: "65.33",
    img: "https://openmusic-fake-api.onrender.com/_id5.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 6,
    title: "Kind of Blue",
    genre: "Jazz",
    band: "Miles Davis",
    price: "61.08",
    img: "https://openmusic-fake-api.onrender.com/_id6.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 7,
    title: "The Wall",
    genre: "Rock",
    band: "Pink Floyd",
    price: "123.56",
    img: "https://openmusic-fake-api.onrender.com/_id7.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 8,
    title: "Abbey Road",
    genre: "Rock",
    band: "The Beatles",
    price: "66.53",
    img: "https://openmusic-fake-api.onrender.com/_id8.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 9,
    title: "Legend",
    genre: "Reggae",
    band: "Bob Marley & The Wailers",
    price: "114.01",
    img: "https://openmusic-fake-api.onrender.com/_id9.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 10,
    title: "Illmatic",
    genre: "Rap",
    band: "Nas",
    price: "138.66",
    img: "https://openmusic-fake-api.onrender.com/_id10.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 11,
    title: "To Pimp a Butterfly",
    genre: "Rap",
    band: "Kendrick Lamar",
    price: "102.66",
    img: "https://openmusic-fake-api.onrender.com/_id11.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 12,
    title: "Groove Theory",
    genre: "R&B",
    band: "Groove Theory",
    price: "139.14",
    img: "https://openmusic-fake-api.onrender.com/_id12.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 13,
    title: "All Eyez on Me",
    genre: "Hip-Hop",
    band: "2Pac",
    price: "50.13",
    img: "https://openmusic-fake-api.onrender.com/_id13.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 14,
    title: "Doo-Wops & Hooligans",
    genre: "Pop",
    band: "Bruno Mars",
    price: "107.28",
    img: "https://openmusic-fake-api.onrender.com/_id14.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 15,
    title: "Dom de Sambar",
    genre: "Samba",
    band: "Turma do Pagode",
    price: "51.67",
    img: "https://openmusic-fake-api.onrender.com/_id15.jpg",
    qtd: 0,
    QTD: 10,
  },
  {
    id: 16,
    title: "Construção",
    genre: "MPB",
    band: "Chico Buarque",
    price: "119.16",
    img: "https://openmusic-fake-api.onrender.com/_id16.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 17,
    title: "Cantar",
    genre: "MPB",
    band: "Gal Costa",
    price: "88.86",
    img: "https://openmusic-fake-api.onrender.com/_id17.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 18,
    title: "Blink-182",
    genre: "Rock",
    band: "Blink-182",
    price: "67.38",
    img: "https://openmusic-fake-api.onrender.com/_id18.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 19,
    title: "Dysphoria",
    genre: "Eletrônica",
    band: "Crywolf",
    price: "143.18",
    img: "https://openmusic-fake-api.onrender.com/_id19.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 20,
    title: "Recess",
    genre: "Eletrônica",
    band: "Skrillex",
    price: "117.44",
    img: "https://openmusic-fake-api.onrender.com/_id20.jpg",
    qtd: 0,
    estoque: 10,
  },
  {
    id: 21,
    title: "Let's Cheers To This",
    genre: "Pop Rock",
    band: "Sleeping With Sirens",
    price: "117.44",
    img: "https://openmusic-fake-api.onrender.com/_id21.jpg",
    qtd: 0,
    estoque: 10,
  },
];